// SPDX-License-Identifier: AGPL-3.0-or-later
// Additional permission: see Stores Exception in LICENSE.
package space.getsub.core.data.db

import androidx.room.Dao
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Upsert
import kotlinx.coroutines.flow.Flow

/** The three Room rows that make up one app-level DNS resolver. */
internal data class DnsSettingSnapshot(
    val transport: String?,
    val domain: String?,
    val ip: String?,
) {
    override fun toString(): String =
        "DnsSettingSnapshot(transport=$transport, domain=<redacted>, ip=<redacted>)"
}

/**
 * Data access for [SettingEntity].
 *
 * A bare [Upsert] is safe here, unlike [ProfileDao.upsertProfile]: `key` is
 * the primary key and every caller supplies it explicitly, so there is no
 * autogenerated-id-of-0 case for Room's conflict fallback to miss.
 */
@Dao
internal interface SettingDao {
    /** The current value for `key`, or null if unset. Emits again on write. */
    @Query("SELECT value FROM settings WHERE `key` = :key")
    fun observe(key: String): Flow<String?>

    /**
     * Observes all DNS setting keys as one query result, never as independently
     * invalidated rows that a collector could combine into a torn resolver.
     */
    @Query(
        """
        SELECT
            (SELECT value FROM settings WHERE `key` = 'dns_transport') AS transport,
            (SELECT value FROM settings WHERE `key` = 'dns_domain') AS domain,
            (SELECT value FROM settings WHERE `key` = 'dns_ip') AS ip
        """,
    )
    fun observeDnsSnapshot(): Flow<DnsSettingSnapshot>

    /** One-shot counterpart used by transactional compare-and-set operations. */
    @Query("SELECT value FROM settings WHERE `key` = :key")
    suspend fun value(key: String): String?

    /** Inserts or overwrites a setting. */
    @Upsert
    suspend fun put(setting: SettingEntity)

    /** Writes every DNS resolver field in one Room transaction. */
    @Transaction
    suspend fun putDnsSnapshot(
        transport: String,
        domain: String,
        ip: String,
    ) {
        put(SettingEntity(key = "dns_transport", value = transport))
        put(SettingEntity(key = "dns_domain", value = domain))
        put(SettingEntity(key = "dns_ip", value = ip))
    }

    /** Atomically claims an unset/null-reading numeric setting for [value]. */
    @Transaction
    suspend fun putIfNoNumericValue(
        key: String,
        value: Long,
    ): Boolean {
        if (this.value(key)?.toLongOrNull() != null) return false
        put(SettingEntity(key, value.toString()))
        return true
    }

    /** Clears [key] only while it still contains [expected], returning the changed-row count. */
    @Query("UPDATE settings SET value = '' WHERE `key` = :key AND value = :expected")
    suspend fun clearIfValue(
        key: String,
        expected: String,
    ): Int
}
