// SPDX-License-Identifier: AGPL-3.0-or-later
// Additional permission: see Stores Exception in LICENSE.
package art.yniyniyni.subspace.core.data.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

/**
 * Data access for [ProfileGroupEntity] and [ProfileEntity].
 *
 * Task 7's [SubspaceDatabaseTest] needed only insert, upsert, cascade-delete
 * a group, and count rows. Task 8 adds the read/query surface the Servers
 * screen and Task 9's repositories actually consume: observable lists, a
 * single-row lookup, per-group deletion, and the two narrow `:bg` writes
 * from spec D4 ([recordConnected], [recordError]).
 */
@Suppress("TooManyFunctions") // A DAO's surface area is the width of its table's usage, not a code smell.
@Dao
internal interface ProfileDao {
    /** Every group, in display order. Recomposes the Servers screen on write. */
    @Query("SELECT * FROM profile_groups ORDER BY position, id")
    fun observeGroups(): Flow<List<ProfileGroupEntity>>

    /** Every profile across every group, in display order. */
    @Query("SELECT * FROM profiles ORDER BY position, id")
    fun observeProfiles(): Flow<List<ProfileEntity>>

    /**
     * Every profile whose [ProfileEntity.name], [ProfileEntity.address] or
     * [ProfileEntity.transport] contains [query] (case-insensitive) and whose
     * [ProfileEntity.protocol] equals [protocol], in display order.
     *
     * Matched against the shadow columns, not the deserialized outbound —
     * see [ProfileEntity]'s own KDoc for why those columns exist. A blank
     * [query] and a `null` [protocol] both mean "no filter", so this is a
     * strict superset of [observeProfiles]: the Servers screen (Task 18)
     * calls it with real values, every other existing caller keeps calling
     * the no-arg overload above unchanged.
     */
    @Query(
        """
        SELECT * FROM profiles
        WHERE (:query = '' OR name LIKE '%' || :query || '%' COLLATE NOCASE
            OR address LIKE '%' || :query || '%' COLLATE NOCASE
            OR transport LIKE '%' || :query || '%' COLLATE NOCASE)
          AND (:protocol IS NULL OR protocol = :protocol)
        ORDER BY position, id
        """,
    )
    fun observeProfiles(
        query: String,
        protocol: String?,
    ): Flow<List<ProfileEntity>>

    /** A single profile by its primary key, or null if it no longer exists. */
    @Query("SELECT * FROM profiles WHERE id = :id")
    suspend fun profile(id: Long): ProfileEntity?

    /** Inserts a group, returning its generated row id. */
    @Insert
    suspend fun insertGroup(group: ProfileGroupEntity): Long

    /**
     * Overwrites an existing group, matched by its primary key.
     *
     * Added for Task 9's `ProfileRepository.renameGroup`: Task 7/8 never
     * needed to mutate a group after creation (insert and cascade-delete were
     * enough for the DAO-level tests), so no update path existed yet. Plain
     * [Update] is safe here the same way [updateImportedProfile] is — the caller
     * always supplies the row's real `id`, so there is no autogenerated-id-of-0
     * case to worry about the way there is in [upsertProfile].
     */
    @Update
    suspend fun updateGroup(group: ProfileGroupEntity)

    /** Inserts a profile, returning its generated row id. */
    @Insert
    suspend fun insertProfile(profile: ProfileEntity): Long

    /**
     * Inserts a profile, or overwrites the existing row's data in place if
     * one already occupies the same (groupId, identityHash) slot — see
     * [ProfileEntity]'s unique index.
     *
     * Deliberately not a bare `@Upsert`. Room's generated conflict fallback
     * for `@Upsert` runs `UPDATE ... WHERE id = <the passed entity's own
     * id>`, and a freshly constructed [ProfileEntity] — the realistic shape
     * for a re-imported or subscription-refreshed profile — has `id = 0`.
     * On conflict that fallback update then matches no row and the write
     * silently vanishes: no exception, no log, just data that never landed.
     * Looking the real row up by identity first and writing through its
     * actual id avoids that trap entirely.
     *
     * [Transaction]ed because this is read-then-write across two statements.
     * Task 9's repository calls this concurrently during subscription
     * import: without a transaction, two coroutines upserting the same
     * (groupId, identityHash) can both see [findProfile] return null before
     * either inserts, and the second insert then throws
     * `SQLiteConstraintException` on the unique index — trading the old
     * silent-drop bug for an unhandled crash. Wrapping both statements in one
     * transaction serializes concurrent callers instead.
     *
     * On the update branch, [ProfileEntity.lastConnectedAt], [ProfileEntity.lastError] and
     * [ProfileEntity.createdAt] are carried over from [existing] rather than taken from
     * [profile] (fix round 2, Important finding 1). [profile] here is freshly built by
     * `ProfileRepository.import` from what the *source* (a subscription, a pasted link)
     * describes and always sets those three columns as if the row were new — correct the
     * first time a given identity is imported, wrong on a re-import: the row already in
     * this slot may carry connection history the device learned since, and a plain
     * full-row overwrite erased it (re-importing a subscription reset every profile's
     * "last used" to never-used and restamped its creation time). Every other column still
     * comes from [profile], since those genuinely describe what the source says now — a
     * renamed or re-keyed server, an updated `rawJson` — same as before this fix.
     */
    @Transaction
    suspend fun upsertProfile(profile: ProfileEntity) {
        val existing = findProfile(profile.groupId, profile.identityHash)
        if (existing != null) {
            updateImportedProfile(
                profile.copy(
                    id = existing.id,
                    lastConnectedAt = existing.lastConnectedAt,
                    lastError = existing.lastError,
                    createdAt = existing.createdAt,
                ),
            )
        } else {
            insertProfile(profile)
        }
    }

    /**
     * Looks up a profile by its (groupId, identityHash) slot — see
     * [ProfileEntity]'s unique index. [upsertProfile] uses this to find the
     * real row id to update; it also lets tests prove an upsert's data
     * actually landed, not just that the row count stayed put.
     */
    @Query("SELECT * FROM profiles WHERE groupId = :groupId AND identityHash = :identityHash")
    suspend fun findProfile(
        groupId: Long,
        identityHash: String,
    ): ProfileEntity?

    /**
     * Overwrites an import-owned row, matched by its primary key.
     *
     * This full-row write is confined to [upsertProfile]'s transaction. The transaction reads the
     * current row and writes the imported replacement as one serialized operation while explicitly
     * carrying connection-owned fields forward. User/editor setters must use the targeted queries
     * below so a `:bg` connection update can never be reverted by a stale entity snapshot.
     */
    @Update
    suspend fun updateImportedProfile(profile: ProfileEntity)

    /** Moves a profile without writing payload, provenance, or connection-owned columns. */
    @Query("UPDATE profiles SET groupId = :toGroupId WHERE id = :id")
    suspend fun moveProfile(
        id: Long,
        toGroupId: Long,
    )

    /** Renames a profile without writing any other column. */
    @Query("UPDATE profiles SET name = :name WHERE id = :id")
    suspend fun renameProfile(
        id: Long,
        name: String,
    )

    /**
     * Updates only the fields owned by the typed profile editor. Kind, raw bytes, group/order,
     * provenance, timestamps, and connection history remain database-owned and untouched.
     */
    @Query(
        """
        UPDATE profiles SET
            name = :name,
            protocol = :protocol,
            address = :address,
            port = :port,
            transport = :transport,
            outbound = :outbound,
            identityHash = :identityHash
        WHERE id = :id
        """,
    )
    @Suppress("LongParameterList") // One parameter per typed-editor-owned column in this update.
    suspend fun updateTypedProfile(
        id: Long,
        name: String,
        protocol: String,
        address: String,
        port: Int,
        transport: String,
        outbound: String,
        identityHash: String,
    )

    /**
     * Deletes a group by id. `ON DELETE CASCADE` on [ProfileEntity]'s foreign
     * key removes every profile in it as part of the same statement.
     */
    @Query("DELETE FROM profile_groups WHERE id = :groupId")
    suspend fun deleteGroup(groupId: Long)

    /** Deletes a single profile by id. */
    @Query("DELETE FROM profiles WHERE id = :id")
    suspend fun deleteProfile(id: Long)

    /** Total profile row count across every group. */
    @Query("SELECT COUNT(*) FROM profiles")
    suspend fun profileCount(): Int

    /**
     * Records a successful connection and clears any prior error. The only
     * write `:bg` performs on this table besides [recordError] — see spec D4.
     */
    @Query("UPDATE profiles SET lastConnectedAt = :at, lastError = NULL WHERE id = :id")
    suspend fun recordConnected(
        id: Long,
        at: Long,
    )

    /**
     * Records a connection failure. `error` must never contain config
     * contents (ARCHITECTURE.md §5.6) — callers pass a category, not the
     * underlying exception message.
     */
    @Query("UPDATE profiles SET lastError = :error WHERE id = :id")
    suspend fun recordError(
        id: Long,
        error: String,
    )

    /**
     * Records why a `RAW_JSON` row cannot run as written, or clears the verdict
     * with `null`.
     *
     * [reason] is a [art.yniyniyni.subspace.core.parser.PassthroughRejection]'s
     * `name`, not the enum itself: this module owns no dependency on
     * `:core:parser`'s call sites outside `ProfileRepository`, and `:service`
     * (Task 8) writes here after the real core refuses a config without
     * otherwise depending on that module.
     */
    @Query("UPDATE profiles SET passthroughRejection = :reason WHERE id = :id")
    suspend fun setPassthroughRejection(
        id: Long,
        reason: String?,
    )
}
