// SPDX-License-Identifier: AGPL-3.0-or-later
package art.yniyniyni.subspace.core.data.db

import androidx.room.Dao
import androidx.room.Query
import androidx.room.Upsert
import kotlinx.coroutines.flow.Flow

/**
 * Data access for [SettingEntity].
 *
 * A bare [Upsert] is safe here, unlike [ProfileDao.upsertProfile]: `key` is
 * the primary key and every caller supplies it explicitly, so there is no
 * autogenerated-id-of-0 case for Room's conflict fallback to miss.
 */
@Dao
internal interface SettingDao {
    /** The current value for `key`, or null if unset. Emits again on write. */
    @Query("SELECT value FROM settings WHERE `key` = :key")
    fun observe(key: String): Flow<String?>

    /** Inserts or overwrites a setting. */
    @Upsert
    suspend fun put(setting: SettingEntity)
}
